# Называем workflow
name: pw test

# Когда мы запускаем автотесты
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # ручной запуск
  workflow_dispatch:
jobs:
  e2eTests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      # делаем чекаут
      - uses: actions/checkout@v4
      # устанавливаем nodejs
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      # устанавливаем пакеты node
      - name: Установить пакеты
        run: npm i
      # устанавливаем PW
      - name: Установить PW
        run: npx playwright install --with-deps
      - name: Запустить PW
        run: npm run test
      # Сохраняем отчет PW
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: test-results
          path: test-results
          retention-days: 20
      # Сохраняем результаты Allure
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: allure-results
          path: allure-results
          retention-days: 20
      # забираем результаты предыдущего запуска
      - uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages     
      # Формируем из allure-results отчет allure-report
      - uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure_results
          gh_pages: gh_pages
          allure_report: allure_report
          allure_history: allure_history
          keep_reports: 20
      # Деплоим отчет
      - name: deploy report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_branch: gh-pages
          publish_dir: allure-history
